services:
  router: Framework\Module\Router\Router

extensions:
  router: Framework\Module\Router\Extension\RouterExtension

listeners:
  kernel.request: Framework\Module\Router\Listener\RequestListener