services:
  router: Framework\Module\Router\Router
  request_listener: Framework\Module\Router\Listener\RequestEventListener

extensions:
  router: Framework\Module\Router\Extension\RouterExtension

listeners:
  event.request: request_listener:onRequest