services:
  memcached:
    builder: Framework\Cache\MemcachedBuilder

  twig:
    builder: Framework\View\TwigBuilder

  doctrine:
    class: Framework\Database\ORM\Doctrine

  database.migrations:
    class: Framework\Database\Migrations

configuration:
  doctrine:
    driver: mysql_pdo
    user: default
    password: default
    dbname: default

  twig:
    debug: true
    paths: /

  memcached:
    host: 127.0.0.1
    port: 11211

commands:
  database.migrations.migrate:
    class: Framework\Database\Command\MigrateCommand:migrate

  database.migrations.status:
    class: Framework\Database\Command\MigrateCommand:status

  database.migrations.generate:
    class: Framework\Database\Command\MigrateCommand:generate

  doctrine:
    class: Framework\Database\Command\MigrateCommand:schema