services:
  memcached:
    builder: Framework\Cache\MemcachedBuilder
    configuration:
      host: 127.0.0.1
      port: 11211

  twig:
    builder: Framework\View\TwigBuilder
    configuration:
      debug: true
      paths: /

  doctrine:
    class: Framework\Database\ORM\Doctrine
    configuration:
      driver: mysql_pdo
      user: default
      password: default
      dbname: default

  database.migrations:
    class: Framework\Database\Migrations

commands:
  database.migrations.migrate:
    class: Framework\Database\Command\MigrateCommand:migrate

  database.migrations.status:
    class: Framework\Database\Command\MigrateCommand:status

  database.migrations.generate:
    class: Framework\Database\Command\MigrateCommand:generate

  doctrine:
    class: Framework\Database\Command\MigrateCommand:schema