services:
  database.manager:
    class: Framework\Core\Database\Manager
  database.migrations:
      class: Framework\Core\Database\Migrations

commands:
  database.migrations.migrate:
    class: Framework\Core\Database\Command\MigrateCommand:migrate
  database.migrations.status:
      class: Framework\Core\Database\Command\MigrateCommand:status
  database.migrations.generate:
      class: Framework\Core\Database\Command\MigrateCommand:generate

parameters:
  database:
    host: 192.168.0.200
    name: application
    user: root
    password:

  migrations:
    directoryPath: migrations
    tableName: versions