services:
  memcached:
    class: Framework\Cache\MemcachedBuilder

  twig:
    class: Framework\View\TwigBuilder

  doctrine:
    class: Framework\Database\ORM\Doctrine

  router:
    class: Framework\Router\Router

  database.migrations:
    class: Framework\Database\Migrations

memcached:
  host: 127.0.0.1
  port: 11211

twig:
  debug: true
  paths: /

doctrine:
  driver: pdo_mysql
  user: default
  password: default
  dbname: default
  cache: false

routes:


commands:
  doctrine_schema_update: Framework\Database\ORM\Doctrine\Command\UpdateSchemaCommand