routes:
  user_register:
    method: POST
    pattern: /api/users
    controller: Application\User\Controller\SecurityController:register

  user_login:
    method: POST
    pattern: /api/login
    controller: Application\User\Controller\SecurityController:login

command:
  database.migrate:
    class: Application\Common\Command\MigrateCommand